import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./context/ReduxProvider";
import ToasterContext from "./context/ToasterProvider";
import Provider from "./context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Future",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
      <ReduxProvider>
      <Provider>
          <ToasterContext />
          
          {children}
        </Provider>
        </ReduxProvider>
        </body>
    </html>
  );
}
